name: Daily Job Digest

on:               # when to trigger
  schedule:
    - cron: "0 8 * * *"" cd /home/mitochondria/Desktop/Learning/job_aggregator && /home/mitochondria/Desktop/Learning/job_aggregator/job_aggregator_project/bin/python main.py


jobs:
  run:
    runs-on: ubuntu-latest   

    env:
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}

    steps:                  
      - name: Checkout code
        uses: actions/checkoutv3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run job aggregator
        run: python main.py
